edition = "2021"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Line width
max_width = 100
wrap_comments = true
comment_width = 100

# Trailing commas / semicolons
trailing_comma = "Vertical"
trailing_semicolon = true

# Braces & blocks
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false

# Function signatures
fn_args_layout = "Tall"
where_single_line = false

# Misc
newline_style = "Unix"
use_small_heuristics = "Default"
normalize_comments = true
normalize_doc_attributes = true
format_macro_matchers = true
hex_literal_case = "Upper"
